export type Style = "minimal" | "retro" | "bold" | "sporty";
export type Usage = "city" | "beach" | "driving" | "mountain";
export type Shape = "round" | "square" | "aviator" | "catEye" | "wayfarer";
export type Palette = "warm" | "cool" | "mono" | "colorful";

export type Product = {
  id: string;
  name: string;
  tagline: string;
  style: Style;
  usage: Usage[];
  shape: Shape;
  palette: Palette;
  frameColor: string;
  lensColor: string;
};

export const products: Product[] = [
  {
    id: "orion",
    name: "Orion",
    tagline: "Clean circles, quiet presence",
    style: "minimal",
    shape: "round",
    palette: "mono",
    usage: ["city", "driving"],
    frameColor: "#1a1a1a",
    lensColor: "#2a2a2a",
  },
  {
    id: "nova",
    name: "Nova",
    tagline: "Polished steel, soft light",
    style: "minimal",
    shape: "round",
    palette: "cool",
    usage: ["city"],
    frameColor: "#7c8a98",
    lensColor: "#4a5c70",
  },
  {
    id: "helio",
    name: "Helio",
    tagline: "Vintage warmth, modern poise",
    style: "retro",
    shape: "catEye",
    palette: "warm",
    usage: ["beach", "city"],
    frameColor: "#a86b3a",
    lensColor: "#3a2810",
  },
  {
    id: "vega",
    name: "Vega",
    tagline: "Highway icon, gold edge",
    style: "retro",
    shape: "aviator",
    palette: "warm",
    usage: ["driving", "city"],
    frameColor: "#c8a25b",
    lensColor: "#2a3a1c",
  },
  {
    id: "atlas",
    name: "Atlas",
    tagline: "Architectural lines, monoblack",
    style: "bold",
    shape: "square",
    palette: "mono",
    usage: ["city"],
    frameColor: "#0a0a0a",
    lensColor: "#1a1a1a",
  },
  {
    id: "lyra",
    name: "Lyra",
    tagline: "Statement frame, sun-soaked",
    style: "bold",
    shape: "square",
    palette: "colorful",
    usage: ["beach", "city"],
    frameColor: "#c43a4a",
    lensColor: "#2a3a5a",
  },
  {
    id: "sirius",
    name: "Sirius",
    tagline: "Built to chase wind",
    style: "sporty",
    shape: "wayfarer",
    palette: "mono",
    usage: ["driving", "mountain"],
    frameColor: "#1a1a1a",
    lensColor: "#1a2a3a",
  },
  {
    id: "andro",
    name: "Andro",
    tagline: "Cold-air clarity",
    style: "sporty",
    shape: "wayfarer",
    palette: "cool",
    usage: ["mountain", "beach"],
    frameColor: "#3a4a5a",
    lensColor: "#1a3a4a",
  },
  {
    id: "calix",
    name: "Calix",
    tagline: "Quiet geometry, weekday-ready",
    style: "minimal",
    shape: "square",
    palette: "mono",
    usage: ["city"],
    frameColor: "#2a2a2a",
    lensColor: "#3a3a3a",
  },
  {
    id: "mira",
    name: "Mira",
    tagline: "Soft tortoise, gentle lift",
    style: "retro",
    shape: "catEye",
    palette: "warm",
    usage: ["city", "beach"],
    frameColor: "#7a4a28",
    lensColor: "#4a2a14",
  },
  {
    id: "polaris",
    name: "Polaris",
    tagline: "Cold peak, sharp line",
    style: "sporty",
    shape: "aviator",
    palette: "mono",
    usage: ["mountain", "driving"],
    frameColor: "#1a1a1a",
    lensColor: "#1a1a2a",
  },
  {
    id: "halo",
    name: "Halo",
    tagline: "Rose gold whisper",
    style: "minimal",
    shape: "round",
    palette: "warm",
    usage: ["city"],
    frameColor: "#c98a8a",
    lensColor: "#5a3a3a",
  },
  {
    id: "eos",
    name: "Eos",
    tagline: "Sunrise on the boardwalk",
    style: "retro",
    shape: "round",
    palette: "warm",
    usage: ["beach", "city"],
    frameColor: "#a8722a",
    lensColor: "#c47a1a",
  },
  {
    id: "kairo",
    name: "Kairo",
    tagline: "Color-blocked confidence",
    style: "bold",
    shape: "aviator",
    palette: "colorful",
    usage: ["beach", "city"],
    frameColor: "#2a6a8a",
    lensColor: "#2a4a7a",
  },
  {
    id: "nyx",
    name: "Nyx",
    tagline: "Night-drive black",
    style: "sporty",
    shape: "wayfarer",
    palette: "mono",
    usage: ["driving"],
    frameColor: "#0a0a0a",
    lensColor: "#0a0a0a",
  },
  {
    id: "aether",
    name: "Aether",
    tagline: "Cool restraint, glass-clear",
    style: "minimal",
    shape: "square",
    palette: "cool",
    usage: ["driving", "city"],
    frameColor: "#4a5a6a",
    lensColor: "#2a3a4a",
  },
  {
    id: "zenith",
    name: "Zenith",
    tagline: "Bold cat, cold tone",
    style: "bold",
    shape: "catEye",
    palette: "cool",
    usage: ["city"],
    frameColor: "#1a2a4a",
    lensColor: "#2a3a5a",
  },
  {
    id: "luma",
    name: "Luma",
    tagline: "Sunset on the strip",
    style: "retro",
    shape: "wayfarer",
    palette: "warm",
    usage: ["city", "beach"],
    frameColor: "#8a4a2a",
    lensColor: "#a45a1a",
  },
  {
    id: "solis",
    name: "Solis",
    tagline: "Trail-warm, sun-strong",
    style: "sporty",
    shape: "square",
    palette: "warm",
    usage: ["mountain"],
    frameColor: "#a8632a",
    lensColor: "#5a3a1a",
  },
  {
    id: "crux",
    name: "Crux",
    tagline: "Hard edge, pure black",
    style: "bold",
    shape: "aviator",
    palette: "mono",
    usage: ["driving"],
    frameColor: "#0a0a0a",
    lensColor: "#1a1a1a",
  },
];
